In [10]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import statistics 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
a=pd.read_csv('dataset.csv')
#x1=a.Count 
data2=np.array(a.version)

In [3]:
x3=[]
n=data2.shape[0]
for i in range(n):
    x3.append(a.loc[i,'port'])    
data = list(zip(data2,x3))

In [4]:
# sd=statistics.stdev(x1)
# m=statistics.mean(x1)
# normalized_x1=(x1-m)/sd

In [5]:
label= a.description
# n=normalized_x1.shape[0]
# for i in range(0,n):
#     if normalized_x1[i]>=0 :
#         label.append(1)
#     else :
#         label.append(0)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression()

In [7]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.39


In [8]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[2379    0    0    3    0    0]
 [  32    0    0    0    0    0]
 [1276    0    0    0    0    0]
 [1218    0    0    5    0    0]
 [   1    0    0    0    0    0]
 [1195    0    0    1    0    0]]


In [9]:
print(classification_report(y_test, y_pred))

precision    recall  f1-score   support

           0       0.66      1.00      0.79      2173
           1       0.67      0.00      0.00      1146

    accuracy                           0.66      3319
   macro avg       0.66      0.50      0.40      3319
weighted avg       0.66      0.66      0.52      3319



In [11]:
#SVM Accuracy

from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=0)

svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)

y_pred = svc.predict(X_test)
confusion_matrix2 = confusion_matrix(y_test, y_pred)
print('Accuracy Score:', metrics.accuracy_score(y_test,y_pred))
print(confusion_matrix2)
print(classification_report(y_test, y_pred))

Accuracy Score: 0.38985270049099835
[[2381    0    0    1    0    0]
 [  32    0    0    0    0    0]
 [1276    0    0    0    0    0]
 [1221    0    0    1    0    1]
 [   1    0    0    0    0    0]
 [1194    0    0    2    0    0]]
              precision    recall  f1-score   support

           0       0.39      1.00      0.56      2382
           1       0.00      0.00      0.00        32
           2       0.00      0.00      0.00      1276
           3       0.25      0.00      0.00      1223
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00      1196

    accuracy                           0.39      6110
   macro avg       0.11      0.17      0.09      6110
weighted avg       0.20      0.39      0.22      6110



In [13]:
#DescisionTree

X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=0)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier = classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)
print('Accuracy Score:', metrics.accuracy_score(y_test,y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy Score: 0.6357336547152757
[[2036  137]
 [1072   74]]
