In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import statistics 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [8]:
a=pd.read_csv('dataset.csv')
data1=np.array(a.version)
data2=np.array(a.port)
label=np.array(a.description)

In [9]:
data = list(zip(data1,data2))

In [10]:
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=0)

In [11]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression()

In [12]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.39


In [13]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[2379    0    0    3    0    0]
 [  32    0    0    0    0    0]
 [1276    0    0    0    0    0]
 [1218    0    0    5    0    0]
 [   1    0    0    0    0    0]
 [1195    0    0    1    0    0]]


In [14]:
print(classification_report(y_test, y_pred))

precision    recall  f1-score   support

           0       0.39      1.00      0.56      2382
           1       0.00      0.00      0.00        32
           2       0.00      0.00      0.00      1276
           3       0.56      0.00      0.01      1223
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00      1196

    accuracy                           0.39      6110
   macro avg       0.16      0.17      0.09      6110
weighted avg       0.26      0.39      0.22      6110



In [15]:
#SVM Accuracy

from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=0)

svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)

y_pred = svc.predict(X_test)
print('Accuracy Score:', metrics.accuracy_score(y_test,y_pred))
print(classification_report(y_test, y_pred))

Accuracy Score: 0.38985270049099835
              precision    recall  f1-score   support

           0       0.39      1.00      0.56      2382
           1       0.00      0.00      0.00        32
           2       0.00      0.00      0.00      1276
           3       0.25      0.00      0.00      1223
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00      1196

    accuracy                           0.39      6110
   macro avg       0.11      0.17      0.09      6110
weighted avg       0.20      0.39      0.22      6110



In [39]:
#DescisionTree

X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=0)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier = classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)
print('Accuracy Score:', metrics.accuracy_score(y_test,y_pred))


Accuracy Score: 0.3888707037643208
